### ISSUE TITLE
Command line call causes divide by Zero error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pageseeder/diffx#3]
```
What steps will reproduce the problem?

Invoke Diffx on the command line with some short XML documents:
  java -jar diffx-0.7.4.jar Main -o out.xml a.xml b.xml

What is the expected output? What do you see instead?

Expected diff report, but got exception:

java.lang.ArithmeticException: / by zero
        at com.topologi.diffx.algorithm.DiffXFitsy.length(DiffXFitsy.java:116)
        at com.topologi.diffx.algorithm.DiffXFitsy.process(DiffXFitsy.java:147)
        at com.topologi.diffx.Main.main(Main.java:317)


What version of the product are you using? On what operating system?

version 0.7.4


```

Original issue reported on code.google.com by `tyenki` on 25 Oct 2010 at 11:08

**Comment by clauret** [comment]
The offending code was removed in 0.9.0
