### ISSUE TITLE
DiffXKumarRangan sometimes fails with IllegalArgumentException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pageseeder/diffx#8]
```
This happens when comparing some content with DiffXKumarRangan. (I will try to 
find a sample to attach. Right now the content I'm working with is proprietary 
to a client. I think it happens pretty easily though and the stacktrace 
probably is enough.)

This was on Ubuntu 14.04 LTS x64, with jdk 1.7

The stacktrace:

java.lang.IllegalArgumentException: Cannot write attribute: too late!
    at com.topologi.diffx.xml.XMLWriterNSImpl.attribute(XMLWriterNSImpl.java:321)
    at com.topologi.diffx.event.impl.AttributeEventNSImpl.toXML(AttributeEventNSImpl.java:151)
    at com.topologi.diffx.format.SmartXMLFormatter.format(SmartXMLFormatter.java:110)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.getLCSMinimumWaste(DiffXKumarRangan.java:336)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.generateLCS(DiffXKumarRangan.java:269)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.getLCSMoreWaste(DiffXKumarRangan.java:399)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.generateLCS(DiffXKumarRangan.java:273)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.getLCSMoreWaste(DiffXKumarRangan.java:398)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.generateLCS(DiffXKumarRangan.java:273)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.getLCSMoreWaste(DiffXKumarRangan.java:398)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.generateLCS(DiffXKumarRangan.java:273)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.getLCSMoreWaste(DiffXKumarRangan.java:398)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.generateLCS(DiffXKumarRangan.java:273)
    at com.topologi.diffx.algorithm.DiffXKumarRangan.process(DiffXKumarRangan.java:127)

```

Original issue reported on code.google.com by `ericjswr...@gmail.com` on 30 Sep 2014 at 10:50

**Comment by clauret** [comment]
Sorry we didn't see those when we migrated away from Google code. All algorithms have been reviewed, and many bugs have been fixed with extensive tests. So I'm closing this old issue.
